# LeakBlock, by Yellow.
# This plugin's purpose is to block the use of the MCLeaks proxies to evade bans on compromised accounts.
#
# Please keep in mind that the ip-api.com API has a limit of 150 connections per minute.
# If your server is exceeding that, you need to contact them.
# More info about that on the Spigot resource page.

# The kick message is simply a way for you to configure the kick message. Use "\n" (without quotation marks) to signify a new line.
# Use "&" color codes.
# If the kick message is "default", the kick message will be set to the default value.
kickMessage: "default"
# If the API returns a failed result, that player will be allowed to connect, and you will get a console message if debugging is enabled.
debug: false
# updatecheck refers to if the plugin will automatically check for updates. This is HIGHLY recommended to be left as true, to keep on top of the MCLeaks proxy.
updatecheck: true
# config version - do not touch it or your config might get reset
configversion: 2
